global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: exporter-metrics
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
    scheme: http
    timeout: 10s
rule_files:
- /etc/prometheus-rules/*.yaml
scrape_configs:
- job_name: Cadvisor
  static_configs:
  - targets:
    - 172.22.101.2:9101
    labels:
      environment_id: 1a5
      environment_name: Default
- job_name: NodeExporter
  static_configs:
  - targets:
    - 172.22.101.2:9100
    labels:
      environment_id: 1a5
      environment_name: Default
- job_name: RancherHealthExporter
  static_configs:
  - targets:
    - 172.22.101.2:9173
    labels:
      environment_id: 1a5
      environment_name: Default
- job_name: RancherServerMetrics
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - rancher-server:9108
- job_name: Prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 127.0.0.1:9090
